title: Quiddity
baseurl: "/quiddity"
url: "https://arcustangens.github.io"

plugins:
  - jekyll-feed

collections:

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
