title: Quiddity
description: A collection of poems exploring the essence of human experience through verse.
baseurl: "/quiddity"    # the subpath for GitHub Pages
url: "https://arcustangens.github.io"   # your GitHub Pages URL

plugins:
  - jekyll-feed

collections:

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
